### PR TITLE
added level_order_traversal_binary_tree.py for issue #192 in Code/Python

### PR DESCRIPTION
**Pull request by sakshi2707**

### CODE REVIEW

**Comment by sakshi2707** [comment]
closes #192 
@plazzy99 I've made requested changes

**Review by plazzy99 — CHANGES_REQUESTED** [review]
Update the readme for the above code

**Comment by sakshi2707** [comment]
@plazzy99  I've updated the readme. 
Please review my PR and add gssoc & level labels. Thankyou

**Review by plazzy99 — APPROVED** [review]

**Comment by sakshi2707** [comment]
Thankyou so much :)
Can you please add gssoc and level labels? @plazzy99

**Pull request merged**
