### PR TITLE
Merging two sorted arrays #1088

### PR DESCRIPTION
**Pull request by ShrutiOmer**
I have added the code for merging the two sorted arrays in constant space in O(1) space in C++ folder in file merge_in_constant_space and changed the Array readme.

issue#1088
Please merge the files.

### CODE REVIEW

**Comment by tarun26091999** [comment]
#1088

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
at atleast 2 testcases. add comments to explain your approach. check the time complexity again and resolve the conflict.

**Comment by ShrutiOmer** [comment]
Ok, I will work on it

**Comment by ShrutiOmer** [comment]
I have made the changes as requested please review it.

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
you don't have to give examples at the top. adding 2 testcases is fine.

**Comment by ShrutiOmer** [comment]
I have removed the example as suggested , please review it again.

**Review by tarun26091999 — APPROVED** [review]

**Pull request merged**
