### PR TITLE
Create construct_by_inorder_n_preorder.py

### PR DESCRIPTION
**Pull request by Aarti002**
-Binary-tree
-Python

### CODE REVIEW

**Comment by Aarti002** [comment]
@tarun26091999 can you review my code and please let me know if something is wrong.

**Comment by Aarti002** [comment]
#321 @tarun26091999 sir please  review and merge my code.
Thank u!

**Comment by tarun26091999** [comment]
you cannot have commits of so many codes in a single PR.

**Comment by Aarti002** [comment]
@tarun26091999 sir can u help how to make different commit in different PRs?
I was confused in this from the beginning please sir i need help!

**Comment by Aarti002** [comment]
Also can i do it again?

**Pull request closed without merging**
