### PR TITLE
Row wise sum in 2d array

### PR DESCRIPTION
**Pull request by Ritikakatoch0128**
@OjusWiZard @rudrakshi99  I have added code to find the row wise sum in 2d array for issue #857  .Kindly review it .

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
cannot add solution of multiple issues in same PR.

**Comment by Ritikakatoch0128** [comment]
> cannot add solution of multiple issues in same PR.

I have modified the PR .Kindly review now.
@tarun26091999

**Comment by rudrakshi99** [comment]
please resolve merge conflicts.

**Comment by Ritikakatoch0128** [comment]
> please resolve merge conflicts.

@rudrakshi99  I have resolved conflicts .kindly review

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
check time complexity and add space complexity.

**Comment by Ritikakatoch0128** [comment]
> check time complexity and add space complexity.

@tarun26091999 kindly review now. I have done required changes.

**Comment by tarun26091999** [comment]
conflict still present

**Comment by Ritikakatoch0128** [comment]
> conflict still present

@tarun26091999 @rudrakshi99 @raksha009 I have resolved all the conflicts .kindly  review and merge it.

**Review by tarun26091999 — APPROVED** [review]

**Pull request merged**
