### PR TITLE
Removing duplicacy of characters from a word

### LINKED ISSUE #91: Remove the duplicacy from a word

### PR DESCRIPTION
**Pull request by AkanshaUniyal**
fixes #91 . The code is written in Java and using recursive technique.

### CODE REVIEW

**Review by raksha009 — CHANGES_REQUESTED** [review]
Plz go through the guidelines and link the file with its folder :)

**Comment by raksha009** [comment]
> Plz go through the guidelines and link the file with its folder :)

plz make the necessary changes! (You could have a look at already merged prs and have a look at which readme updation I am asking about :))

**Comment by AkanshaUniyal** [comment]
Updated readme.md
@raksha009 can you please tell me is it fine now?

**Comment by raksha009** [comment]
> Updated readme.md
> @raksha009 can you please tell me is it fine now?

No dear, look at the file changes, it shows 1. Also the readme is not updated and the code is also not visible,

**Pull request closed without merging**
