### PR TITLE
N Queens problem in Python

### PR DESCRIPTION
**Pull request by Muskan0**
#381 Please review my PR.

### CODE REVIEW

**Review by plazzy99 — APPROVED** [review]
LGTM 👍

**Comment by plazzy99** [comment]
Resolve conflicts

**Comment by Muskan0** [comment]
@plazzy99 Conflicts resolved, please review and merge.

**Comment by rudrakshi99** [comment]
> @plazzy99 Conflicts resolved, please review and merge.

It is not resolved yet.

**Comment by Muskan0** [comment]
@rudrakshi99 Resolved the conflicts, please merge it.

**Comment by Muskan0** [comment]
@plazzy99 Please review this.

**Pull request merged**
