### PR TITLE
Largest Rectangle Area (Histogram) added in java #161

### PR DESCRIPTION
**Pull request by krishna-NIT**
Largest Rectangle Area (Histogram)
Done in Java #161 Solved
@OjusWiZard @nakul-19 @rudrakshi99 
Please Review it

### CODE REVIEW

**Comment by krishna-NIT** [comment]
@yasharth291 Please review it and please tell me is any changes

**Comment by krishna-NIT** [comment]
@Rohan27s @tarun26091999  Please Review it and Let me Know if any changes

**Comment by tarun26091999** [comment]
copied from https://www.geeksforgeeks.org/largest-rectangle-under-histogram/
exact variable names and comments. Plagrism won't work here.

**Comment by krishna-NIT** [comment]
Yes, Mistake Accepted, Will avoid this in next one @tarun26091999

**Pull request closed without merging**
