### PR TITLE
Diameter Of Binary Tree C++

### PR DESCRIPTION
**Pull request by vanshikachokhani**
### Changes made
I have written recursive approach to find the maximum profit in C++.
This is a contribution as a part of GSSoC21.

I have tested the code and it works fine for every test case and included some sample test cases and also the algorithm.

### CODE REVIEW

**Comment by krishna-NIT** [comment]
@vanshikachokhani Update the Readme which is present at Algo-Tree/Tree/readme.md location, add this question at Last

**Comment by krishna-NIT** [comment]
Arrange Question in Alphabetical Order

**Comment by vanshikachokhani** [comment]
> Arrange Question in Alphabetical Order

I have updated the redme file.

**Comment by krishna-NIT** [comment]
@rish-singhal LGTM

**Pull request merged**
