### PR TITLE
For issue #220

### PR DESCRIPTION
**Pull request by krishna408**
Added **min_deletions_to_make_string_palindrome.cpp** file in Code->C++ folder for issue 220

#220

### CODE REVIEW

**Comment by krishna408** [comment]
I have to provide the link of my code file  in readme.md of C++ folder?

**Comment by krishna408** [comment]
> I have to provide the link of my code file in readme.md of C++ folder?

**Review by krishna408 — COMMENTED** [review]
added file link in readme.md of dp folder

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
issue is not linked.

**Review by krishna408 — COMMENTED** [review]
Linked issue#220  in Code/C++ and DP/readme.md

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
you also need to link your PR with the issue.

**Comment by krishna408** [comment]
#220

**Review by tarun26091999 — APPROVED** [review]

**Comment by krishna408** [comment]
it will be merged @tarun26091999 ?

**Comment by tarun26091999** [comment]
> it will be merged @tarun26091999 ?

yes as soon as @plazzy99 reviews it.

**Review by plazzy99 — APPROVED** [review]

**Pull request merged**
