### PR TITLE
Deleting a Node from Linked List in Java

### LINKED ISSUE #805: GSSOC'21 : Deletion from Linked List
Hi @tarun26091999 
I want to add the following 3 methods to linked list in c++
- [ ] Delete from beginning
- [ ] Delete from end
- [ ] Delete from specific position

I am in GSSOC'21 program

Thanks

### PR DESCRIPTION
**Pull request by khusheekapoor**
Fixes #805

### CODE REVIEW

**Comment by yasharth291** [comment]
please resolve the conflicts and mention your issue as Fixes #805

**Comment by khusheekapoor** [comment]
> please resolve the conflicts and mention your issue as Fixes #805

Made the changes.

**Comment by tarun26091999** [comment]
conflict still present

**Comment by khusheekapoor** [comment]
> conflict still present

made the changes @tarun26091999

**Pull request merged**
