### PR TITLE
Added Cycle Detection Linked List (C++)

### LINKED ISSUE #189: Cycle detection in linked list
Implementation of hare and tortoise algorithm to detect cycle in linked list.

### PR DESCRIPTION
**Pull request by sssash18**
Added Implementation of Hare and tortoise algorithm c++
Fixed #189

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
Give the explanation of the problem at the top. Also link it in appropriate folder. Go through the guidelines before raising a PR.

**Comment by sssash18** [comment]
@tarun26091999  Please check I have made the changes requested.
Sorry If I violated any guidelines previously.

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
As you are working in C++, so you should not use struct, **use Class** in creation of a node. Also there should be at least **2 testcases** present at the bottom.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Are you pushing the same code to multiple different Projects. Here is your PR for NeoAlgo: https://github.com/TesseractCoding/NeoAlgo/pull/2348

If yes, please don't do that. Prefer to stick with one project and don't bug the maintainers with duplicated code across multiple projects. 

Thanks!

**Comment by sssash18** [comment]
> Are you pushing the same code to multiple different Projects. Here is your PR for NeoAlgo: [TesseractCoding/NeoAlgo#2348](https://github.com/TesseractCoding/NeoAlgo/pull/2348)
> 
> If yes, please don't do that. Prefer to stick with one project and don't bug the maintainers with duplicated code across multiple projects.
> 
> Thanks!

Sorry @HarshCasper .Actually this algo was missing in both the projects , so I made a PR in both, I did'nt knew it was unethical. I apologize for the same.

**Comment by sssash18** [comment]
@tarun26091999  I have added the classes please review it.

**Comment by sssash18** [comment]
> > Added Implementation of Hare and tortoise algorithm c++
> > Fixed #189
> 
> output is not correct for this test case: ` ls->head->next->next->next= ls->head;` . Break the cycle at the point of intersection and print the position.

@rudrakshi99 Thanks for your suggestions .Actually I checked the output for your mentioned testcase and it returned "1" which means cycle detected. Please have a look for the screenshot.
Screenshot 2021-03-09 at 10 48 53 PM
Also regarding the printing of index, but the problem only mentions the detection of cycle and not printing the index at which cycle starts.
Please correct me if I am wrong.

**Review by rudrakshi99 — APPROVED** [review]

**Pull request merged**
