### PR TITLE
Book Allocation Problem in C++

### PR DESCRIPTION
**Pull request by snowpanther6**
### Fixed issue  #665 

Changes made
I have written the approach of this problem and also added code in C++ with some sample test cases and also written time and
space complexity of this problem
This is a small contribution as a part of GSSoC21.

I have tested the code and it works fine for every test case and included the complete explanation of the algorithm

### CODE REVIEW

**Review by raksha009 — COMMENTED** [review]
Link your code with the folder.

**Comment by snowpanther6** [comment]
> Link your code with the folder.

In which folder I have to link my code can you say.

**Comment by snowpanther6** [comment]
I have updated the input format and also linked the code to the folder.

**Review by OjusWiZard — APPROVED** [review]

**Comment by OjusWiZard** [comment]
Plagiarised from [GFG](https://www.geeksforgeeks.org/allocate-minimum-number-pages/)

**Pull request closed without merging**
