### PR TITLE
Adding Java Knapsack 

### PR DESCRIPTION
**Pull request by anjali1102**
issue number #1976
output: 
WhatsApp Image 2021-05-27 at 11 35 23 PM

### CODE REVIEW

**Comment by anjali1102** [comment]
@rish-singhal  Kindly review

**Comment by rish-singhal** [comment]
Create 2 separate PRs for python and java

**Comment by anjali1102** [comment]
> Create 2 separate PRs for python and java

Means I need to create new issue for python?

**Comment by rish-singhal** [comment]
It means to create to separate pull request targeting same issue

**Comment by rudrakshi99** [comment]
Please resolve merge conflicts.

**Pull request merged**
