### PR TITLE
Balanced Bracket Problem -> Closes: #[1683]

### PR DESCRIPTION
**Pull request by Prerna-07**
It checks  if the brackets are balanced or not in an expression.
Closes: #1683

### CODE REVIEW

**Comment by rish-singhal** [comment]
refer the issue number as-> Closes: #[issue_number]

**Review by yasharth291 — APPROVED** [review]

**Comment by yasharth291** [comment]
@Prerna-07  please change the readme.md file

**Comment by Prerna-07** [comment]
@yasharth291  ok sir

**Comment by Prerna-07** [comment]
@yasharth291 done

**Pull request closed without merging**
