### PR TITLE
Painting fence in cpp

### LINKED ISSUE #1820: painting fence problem
**Is your feature request related to a problem? Please describe.**
problem statement :
Given a fence with n posts and k colors, find out the number of ways of painting the fence such that at most 2 adjacent posts have the same color. 

**Describe the solution you'd like**
This is a classic problem in dynamic programming

**Do you want to work on it**
I would like to implement this in c++  
Please assign me this issue as part of GSSOC '21

### PR DESCRIPTION
**Pull request by aaadddiii**
Fixes #1820

### CODE REVIEW

**Comment by aaadddiii** [comment]
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal please review my pr

**Review by yasharth291 — APPROVED** [review]

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
answer can be large return it modulo 10^9 + 7 and also add 2 testcases. Also print the exact cout text in testcases.

**Comment by aaadddiii** [comment]
@tarun26091999 I have made the changes can you please review and merge it

**Comment by tarun26091999** [comment]
how the space complexity is O(n)??

**Comment by aaadddiii** [comment]
@tarun26091999  Sorry I have made the changes can you please review my pr

**Comment by rudrakshi99** [comment]
resolve merge conflicts

**Review by rudrakshi99 — APPROVED** [review]

**Pull request merged**
