### PR TITLE
first unique character in a string

### PR DESCRIPTION
**Pull request by Roshni1809**
Hi @tarun26091999  please check the PR( issue #569).

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
add it to appropriate folder.

**Comment by Roshni1809** [comment]
> add it to appropriate folder.

Ok @tarun26091999

**Comment by tarun26091999** [comment]
make the asked changes.

**Comment by Roshni1809** [comment]
> make the asked changes.
ok

**Pull request closed without merging**
