### PR TITLE
Added Word Wrap Problem

### PR DESCRIPTION
**Pull request by ansi22**
Hey @tarun26091999 
Kindly check this out, it will fix issue #427.

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
cannot have commits of 2 issues in 1 PR.

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
code is fine, just make the output easy to understand. Also link the code to appropriate folder.

**Comment by ansi22** [comment]
Hey, @tarun26091999 kindly check it, I have made the requested changes

**Comment by ansi22** [comment]
@tarun26091999 Sir Kindly review this.

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
give the output like this.
Line number 1: From word no. 1 to 3
Line number 2: From word no. 4 to 6
Line number 3: From word no. 7 to 10
Line number 4: From word no. 11 to 14
Line number 5: From word no. 15 to 17
Line number 6: From word no. 18 to 18

and also resolve the conflict.

**Comment by ansi22** [comment]
@tarun26091999 Sir am unable to understand the conflict here can you please let me know how to resolve it.

**Review by tarun26091999 — APPROVED** [review]

**Pull request merged**
