### PR TITLE
 java under GSSOC'2021

### PR DESCRIPTION
**Pull request by pallavidhere23**

### CODE REVIEW

**Comment by pallavidhere23** [comment]
I have resolved the issue of reversing Linkedlist in java language. I have used Iterative method also give well explanatory algorithm of the same in comments .My code is well commented. Time complexity is O(n),space complexity is O(1).

**Comment by pallavidhere23** [comment]
Sorry ,Maám I am new to open source, not getting how to link PR with issue.Would u please help me with this.

**Comment by rudrakshi99** [comment]
@pallavidhere23 No, it's ok.  Just use `#` and type the issue number in the comment description and it will automatically get linked.

**Comment by pallavidhere23** [comment]
trying to solve issue no: #339

**Comment by pallavidhere23** [comment]
#193 issue no

**Comment by raksha009** [comment]
Plz link your code with the readme as well. Have a look at some of the merged prs and make the changes accordingly :)

**Comment by pallavidhere23** [comment]
@raksha,can you please tell me how to link my code with readme.I am new to open source I don't know how can I do so.Also If any other changes are required please tell me.I have checked other merged PRs ,According to me my code is similar,but any changes required please tell me.

**Comment by pallavidhere23** [comment]
@raksha009 ,I tried linking to readme.Please check if its ohk or not.Also please Inform me is my code is ohk to get merged ,if not tell me the changes I need to make.

**Comment by pallavidhere23** [comment]
@rudrakshi99 ,I have made all the changes linked my code in readme also,please if my code needed any more changes tell me or please merge my request with GSSOC'2021 label.

**Comment by pallavidhere23** [comment]
> Bsf traversal commit issue [Algo-Phantoms#248](https://github.com/Algo-Phantoms/Algo-Tree/issues/248)
@tarun26091999 please check this PR

**Review by raksha009 — COMMENTED** [review]
Remove extra files.

**Pull request closed without merging**
