### PR TITLE
Update readme.md -> Closes: #[1683]

### PR DESCRIPTION
**Pull request by Prerna-07**
related pull request ->#1671
closes : #1683

### CODE REVIEW

**Comment by Prerna-07** [comment]
@yasharth291 updated readme for balanced bracket problem

**Comment by Prerna-07** [comment]
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 pls check

**Comment by Rohan27s** [comment]
Resolve the conflicts @Prerna-07

**Comment by Prerna-07** [comment]
@Rohan27s  the main file has no conflict I can't understand why readme file has conflict pls help.

**Comment by Rohan27s** [comment]
check if you have created the pr from your base branch....because I can see that your base branch is deleted

**Comment by Prerna-07** [comment]
@Rohan27s  Yes it is from there, should I update Readme once more?

**Comment by Rohan27s** [comment]
yes, try committing the readme again

**Comment by Prerna-07** [comment]
@Rohan27s  ok.

**Pull request closed without merging**
