### PR TITLE
C++ implementation of subset sum problem using Dynamic programming under gssoc21

### LINKED ISSUE #148: Subset Sum Algorithm using Dynamic Programming
Hello @rudrakshi99 @nakul-19 @plazzy99
I am a GSSoC21 participant.

What I want to contribute :

Optimized approach for Subset Sum Algorithm using Dynamic programming
My code will be in C++
The code will be commented for easy understanding, including 2 test cases
Please assign this issue to me.

### LINKED ISSUE #149: Equal Sum Partition using Dynamic Programming in C++
Hello @rudrakshi99 @nakul-19 @plazzy99
I am a GSSoC21 participant.

What I want to contribute :

Optimized approach for Equal Sum Partition Algorithm using Dynamic programming
My code will be in C++
The code will be commented for easy understanding, including 2 test cases
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by shawavisek35**
Resolves #148 
Added the required code for subset problem and equal sum partition in c++ with proper explanation.

### CODE REVIEW

**Comment by plazzy99** [comment]
Never add level by your own

**Comment by plazzy99** [comment]
Raise 2 seperate issue as 1 pr can contain max 1 issue

**Comment by shawavisek35** [comment]
> Raise 2 seperate issue as 1 pr can contain max 1 issue

I have been assigned to work on both the issues

**Comment by shawavisek35** [comment]
@plazzy99 could please review this pr and if everything is ok then merge it also?

**Comment by shawavisek35** [comment]
@plazzy99 please look after this pr. It's been a week and it has not been reviewed yet.

**Comment by plazzy99** [comment]
> Resolves #148
> Resolves #149
> Added the required code for subset problem and equal sum partition in c++ with proper explanation.

make 2 separate pr for resolving 1 issue each

**Comment by plazzy99** [comment]
> > Raise 2 seperate issue as 1 pr can contain max 1 issue
> 
> I have been assigned to work on both the issues

no problem but you have to raise separate pr.

**Comment by shawavisek35** [comment]
> > > Raise 2 seperate issue as 1 pr can contain max 1 issue
> > 
> > 
> > I have been assigned to work on both the issues
> 
> no problem but you have to raise separate pr.

ok i will raise two different pull request.

**Review by yasharth291 — APPROVED** [review]

**Pull request merged**
