### PR TITLE
Left Rotation of Array Added in JAVA

### PR DESCRIPTION
**Pull request by krishna-NIT**
#402 Solved in JAVA with Feature to Select by how much values you want to Rotate Left
Left Rotation of Array Added in JAVA Added
has choice to select by how many entries you want to rotate array leftwards
@tarun26091999 @rudrakshi99 @nakul-19 @plazzy99 please let me know if any changes

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
use multiple lines to take the input, as testcases are very confusing. Also add comments to explain the steps. Link it to the appropriate folder.

**Review by krishna-NIT — COMMENTED** [review]
Done @tarun26091999 , Please Tell if any

**Comment by krishna-NIT** [comment]
May I know what more changes are required?

**Comment by krishna-NIT** [comment]
@tarun26091999 @nakul-19 @rudrakshi99,
Please Review, All Changes Made in JAVA,
Almost 30 Days Gone
#402

**Comment by shreyanspoddar** [comment]
Resolve the conflict

**Comment by krishna-NIT** [comment]
@shreyanspoddar why it is closed without giving time for changes?

**Pull request closed without merging**
