### PR TITLE
Kth Minimum Element in the Array [C++]

### LINKED ISSUE #162: Kth minimum/maximum element in an array
Hi,
I am a GSSOC'21 participant.
I want to add the various solutions of finding the Kth smallest/largest element in an array. A simple and straightforward that everyone probably knows is simple sorting that takes O(N log N) time.  I will discuss the various implementations in linear time complexity.
* My code will be in C++
* I will add proper test cases explaining every approach to the problem

C++
- [ ] Minimum
- [ ] Maximum

Java
- [ ] Minimum
- [ ] Maximum

Python
- [ ] Minimum
- [ ] Maximum

Please assign me this issue @nakul-19 @plazzy99 @rudrakshi99

### PR DESCRIPTION
**Pull request by vedant-jain03**
Fixes #162 
* Added Code in C++ 
* Checkout all guidelines
* Update Readme file

### CODE REVIEW

**Comment by vedant-jain03** [comment]
@tarun26091999 @raksha009 @plazzy99 @rudrakshi99 Please review my PR

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
this is not the most optimized approach. You took this long to raise the PR and still the solution nowhere near to the required quality. Also there are conflicts in code base.

**Comment by vedant-jain03** [comment]
> this is not the most optimized approach. You took this long to raise the PR and still the solution is nowhere near to the required quality. Also there are conflicts in code base.

Should I use heap to implement this?

**Comment by tarun26091999** [comment]
> > this is not the most optimized approach. You took this long to raise the PR and still the solution is nowhere near to the required quality. Also there are conflicts in code base.
> 
> Should I use heap to implement this?

yes and do it asap

**Pull request closed without merging**
