### PR TITLE
Added Kruskal's Algorithm in java

### PR DESCRIPTION
**Pull request by Ayan-10**
Added Kruskal's Algorithm in java which is a part of #7

### CODE REVIEW

**Review by Siddhant-K-code — APPROVED** [review]
LGTM

**Comment by Ayan-10** [comment]
@Siddhant-K-code Can you tell me what do you mean by LGTM?

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code Can you tell me what do you mean by LGTM?

LGTM Means "Looks Good To Me"

**Comment by shreyanspoddar** [comment]
Resolve the conflict

**Pull request merged**
