### PR TITLE
Three Sum in Python

### PR DESCRIPTION
**Pull request by yashmita**
I have added the code for Three Sum in Python for issue #163 
Kindly review it.

### CODE REVIEW

**Comment by plazzy99** [comment]
REsolve confilicts

**Comment by yashmita** [comment]
> REsolve confilicts

Done.

**Comment by plazzy99** [comment]
> > REsolve confilicts
> 
> Done.
> 

Sorry but you need to it again

**Comment by yashmita** [comment]
@plazzy99 I've resolved the conflicts.

**Pull request merged**
