### PR TITLE
Unique Prime Factors in Java Added

### PR DESCRIPTION
**Pull request by krishna-NIT**
Unique Prime Number in JAVA Added #881
With Description and Comments
Please let me know if any changes

### CODE REVIEW

**Comment by krishna-NIT** [comment]
@tarun26091999  Sir please review it

**Comment by krishna-NIT** [comment]
@tarun26091999 @nakul-19 @rudrakshi99 
Please Review it, more than 7 days been gone 
#881

**Comment by krishna-NIT** [comment]
@yasharth291 Please review it because Daily I get Conflicts in Readme File, I have to Resolve them Daily, Am I making any Mistake in Readme ?, can you please tell me why I am Getting Conflicts in Readme always, coz I am new to GIT and GITHUB

**Review by plazzy99 — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
