### PR TITLE
Implementation of "Counting_Divisors_using_Sieve" and " GCD_using_Euclids_Algorthm " Added

### PR DESCRIPTION
**Pull request by Ritu7683**
@tarun26091999 @rudrakshi99  Please review my Code and tell me if it require some changes or not. Thank you

### CODE REVIEW

**Comment by Ritu7683** [comment]
@tarun26091999 @rudrakshi99 Please Reply

**Comment by Ritu7683** [comment]
@tarun26091999 @rudrakshi99 Please Reply

**Comment by tarun26091999** [comment]
link the issue

**Comment by Ritu7683** [comment]
@tarun26091999 Check issue #559 and #560

**Comment by Ritu7683** [comment]
@tarun26091999 @rudrakshi99 Please reply. I need to generate 2 more PR for other issues in your project.

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
cannot solve 2 issues in 1 PR.

**Pull request closed without merging**
