### PR TITLE
Longest Palindromic Substring Issue-455

### PR DESCRIPTION
**Pull request by Atul-Kashyap**
Hey @tarun26091999 , I added the longest palindromic substring c++ code in the "/Algo-Tree/C++" folder. I write code as per the guidelines. 
Code passed all the test cases and if you find something wrong, please let me know.
Please merge it as soon as you can.
Thank You

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
link the issue

**Review by Atul-Kashyap — COMMENTED** [review]
#816

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
code is fine, link it to the folder.

**Comment by Atul-Kashyap** [comment]
Can you please open it, I forgot about changes.
I will make changes immediately.

**Comment by Atul-Kashyap** [comment]
Hi @tarun26091999 ,
Can you please activate it ?

**Pull request closed without merging**
