### PR TITLE
Issue 535

### PR DESCRIPTION
**Pull request by veenit1802**
@rudrakshi99  mam kindly check the code for any mistake or editing problem for issue-#535

### CODE REVIEW

**Comment by rudrakshi99** [comment]
> @rudrakshi99 mam kindly check the code for any mistake or editing problem for issue-#535

Make separate PRs for both the algorithm.

**Comment by veenit1802** [comment]
Yes,@rudrakshi99  I updated the PR, please check if it is correct.
Thank you.

**Review by rudrakshi99 — APPROVED** [review]

**Comment by rudrakshi99** [comment]
> Yes,@rudrakshi99 I updated the PR, please check if it is correct.
> Thank you.

Update the readme and add the name of the algorithm that you have used for detecting.

**Comment by rudrakshi99** [comment]
@veenit1802 update the list in the readme of the Graph folder.

**Review by tarun26091999 — APPROVED** [review]

**Pull request merged**
