### PR TITLE
Added Code for palindrome checker using doubly linked list in java

### PR DESCRIPTION
**Pull request by Alleny244**

### CODE REVIEW

**Comment by yasharth291** [comment]
issue number and change the readme

**Comment by tarun26091999** [comment]
#346

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
link to folder and correct the heading's indentation.

**Comment by Alleny244** [comment]
> link to folder and correct the heading's indentation.

@tarun26091999 
to which folder should i push the code to

**Comment by Alleny244** [comment]
@tarun26091999 can you specifiy folder location

**Comment by rudrakshi99** [comment]
Update the readme of string folder.

**Comment by Alleny244** [comment]
> Update the readme of the linked list folder.

@rudrakshi99 I HAVE UPDATED THE README.MD OF THE LINKED LIST FOLDER

**Comment by Alleny244** [comment]
> link to folder and correct the heading's indentation.

i HAVE PUSHED TO THE CORRECT FOLDER AND CENTERED THE HEADING

**Pull request merged**
