### PR TITLE
Trimorphic Number in Java [Fixes #1736]

### LINKED ISSUE #1736: Trimorphic Number in Java
**Is your feature request related to a problem? Please describe.**
The program will check whether the number input by the user is trimorphic or not.

**Describe the solution you'd like**
A number n is a trimorphic number if n^3 ends in n.

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

Please assign it to me @rish-singhal @yasharth291 @raksha009 @rudrakshi99 @plazzy99 @OjusWiZard @tarun26091999

### PR DESCRIPTION
**Pull request by khusheekapoor**
Fixes issue #1736 by providing a solution in Java as a GSSoC'21 participant. Please let me know if changes are required. Thanks!

### CODE REVIEW

**Review by Rohan27s — CHANGES_REQUESTED** [review]
Resolve this compilation error 
image

**Comment by khusheekapoor** [comment]
> Resolve this compilation error
> image

made the changes. is it working now? no error is shown in my ide (BlueJ).

**Comment by Rohan27s** [comment]
> > Resolve this compilation error
> > image
> 
> made the changes. is it working now? no error is shown in my ide (BlueJ).

Send the screenshot of the output

**Comment by khusheekapoor** [comment]
> > > Resolve this compilation error
> > > image
> > 
> > 
> > made the changes. is it working now? no error is shown in my ide (BlueJ).
> 
> Send the screenshot of the output

image

**Comment by Rohan27s** [comment]
@khusheekapoor try to run the code on an online compiler and then send me the screenshot

**Comment by khusheekapoor** [comment]
> @khusheekapoor try to run the code on an online compiler and then send me the screenshot

Not working on online compiler. This is the first time I am facing such an error. What should I do?

**Comment by khusheekapoor** [comment]
@Rohan27s found the error
On online compilers (atleast the ones we both used - Programiz), the Class name has to be Main. This is why it shows an error. Is my PR valid now?

**Review by Rohan27s — APPROVED** [review]

**Pull request merged**
