### PR TITLE
Top view bottom view

### LINKED ISSUE #1738: Top View of a Binary Tree
**Is your feature request related to a problem? Please describe.**
If a binary tree is given the output will be the top view of the binary tree. 

**Describe the solution you'd like**
This can be done by assuming that the left and the right child of the node makes a 45-degree angle with the parent. 

**Do you want to work on it**
Python

### PR DESCRIPTION
**Pull request by nidhivanjare**
Code for Top and bottom view a binary tree in python
Fixes #1738

Screenshot 2021-05-04 at 4 05 35 PM

Screenshot 2021-05-04 at 4 04 59 PM

### CODE REVIEW

**Comment by nidhivanjare** [comment]
DONE!! @rish-singhal

**Comment by nidhivanjare** [comment]
@rish-singhal @krishna-NIT 
Are any changes required?

**Comment by krishna-NIT** [comment]
@nidhivanjare  For each issue create a separate branch so that you can make separate pr for each issue.

**Comment by nidhivanjare** [comment]
but this issue is for top view and bottom view 
I have created the PR for the same !!

Do I have to create 2 different PR for Top view and bottom view because I have raised a single issue for both? 

@krishna-NIT

**Comment by nidhivanjare** [comment]
Screenshot 2021-05-05 at 8 17 38 PM

**Comment by krishna-NIT** [comment]
@rish-singhal Please Guide here sir!

**Pull request closed without merging**
