### PR TITLE
[feature-1] staircase_search.cpp

### PR DESCRIPTION
**Pull request by kiruba-r11**
Closes: #385 

Implemented the StairCase Search in C++

- [x] Code is well-formatted
- [x] Code is well commented
- [x] Code is not plagiarised
- [x] Code is placed in the proper folder
- [x] readme.md of 2D_Array is updated with the code link

### CODE REVIEW

**Comment by kiruba-r11** [comment]
@tarun26091999 Please review this and suggest me any changes if required.

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
it need to be linked in the searching folder. Also add comments to explain your steps.

**Comment by kiruba-r11** [comment]
@tarun26091999 I have added comments to my code. And, I am not sure about which searching folder you are saying. Is it the one inside the Algorithms folder? If so, can you please explain to me in detail what changes do I have to make in that folder?

**Comment by kiruba-r11** [comment]
@tarun26091999 Can you please guide me regarding the comment I gave above

**Comment by kiruba-r11** [comment]
@tarun26091999 Please review this

**Comment by kiruba-r11** [comment]
@tarun26091999 Please review this

**Comment by kiruba-r11** [comment]
@tarun26091999 Please review this

**Comment by kiruba-r11** [comment]
@rudrakshi99 Can you please review this

**Comment by rudrakshi99** [comment]
> @tarun26091999 I have added comments to my code. And, I am not sure about which searching folder you are saying. Is it the one inside the Algorithms folder? If so, can you please explain to me in detail what changes do I have to make in that folder?

this one - https://github.com/Algo-Phantoms/Algo-Tree/tree/main/Algorithm/Searching_Sorting

**Review by rudrakshi99 — APPROVED** [review]

**Comment by kiruba-r11** [comment]
@rudrakshi99 I made the changes. Suggest me any more changes if required

**Review by OjusWiZard — CHANGES_REQUESTED** [review]
Please use 4 spaces for indentation.

**Review by tarun26091999 — APPROVED** [review]

**Comment by kiruba-r11** [comment]
@OjusWiZard Please recheck it again. It has been more than 20 days waiting for this PR to get reviewed

**Review by OjusWiZard — APPROVED** [review]
Ok, we have updated our guidelines for the indentation now.
Good work!

**Pull request merged**
