### PR TITLE
Implementation of Counting_Divisors_using_Sieve Added 

### PR DESCRIPTION
**Pull request by Ritu7683**
@tarun26091999 Please review this PR for issue #560

### CODE REVIEW

**Comment by Ritu7683** [comment]
@tarun26091999 I have deleted the previous PRs and opened a new one please review it so that I can open up new PRs in the project

**Comment by Ritu7683** [comment]
for other issues

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
code is fine, add testcases as they will appear on the screen. also link the code to the folder.

**Comment by Ritu7683** [comment]
@tarun26091999 I have already added 2 testcases in comment at the end of the file. 
This code will go in Algorithm folder's Number theory folder.

**Comment by Ritu7683** [comment]
@tarun26091999 Can you tell me how to link the code in folder?

**Comment by tarun26091999** [comment]
> @tarun26091999 Can you tell me how to link the code in folder?

change the readme file of the number theory folder and add the link as others have done.

**Comment by tarun26091999** [comment]
> @tarun26091999 I have already added 2 testcases in comment at the end of the file.
> This code will go in Algorithm folder's Number theory folder.

yes but add the testcases as they will be appear on user's screen.

**Pull request closed without merging**
