### PR TITLE
Added Smallest_Subarray code in java folder

### PR DESCRIPTION
**Pull request by sonalsingh25**
Hi @tarun26091999 I am Sonal Singh a GSSoC participant. I have added the code for smallest subarray in java . I have pushed it into code/java folder with the file name Smallest_Subarray. I am therefore creating a pull request and hereby request you to do what is needed next. My issue number was 504. My folder goes as Code/Java/Smallest_Subarray.java

### CODE REVIEW

**Comment by tarun26091999** [comment]
issue #504

**Comment by sonal251001** [comment]
Hey @tarun26091999 Please add relevant labels. I'm a gssoc participant.

**Comment by sonal251001** [comment]
@shreyanspoddar please review my PR.

**Comment by sonal251001** [comment]
Will this PR get merged? It has been 2 months now?

**Pull request closed without merging**
