### PR TITLE
Diameter_BinaryTree - Java

### LINKED ISSUE #1739: Diameter of a Binary tree
**Is your feature request related to a problem? Please describe.**
To print the diameter of a given binary tree. 

**Describe the solution you'd like**
A binary tree diameter equal to the total number of nodes on the longest path between any 2 nodes in it. 

**Do you want to work on it**
Python

I am a GSSOC'21 Participant and would like to work on this issue.

### PR DESCRIPTION
**Pull request by nidhivanjare**
Code for Diameter Od a binary tree in java and python. 
Fixes #1739 

This PR is for java

JAVA :

Screenshot 2021-04-28 at 3 18 30 PM

### CODE REVIEW

**Comment by nidhivanjare** [comment]
I have created a separate PR for java as you asked me to. 
@krishna-NIT

**Comment by krishna-NIT** [comment]
@nidhivanjare  please dm me on discord

**Comment by nidhivanjare** [comment]
Can I get a link or username ??

**Comment by krishna-NIT** [comment]
> Can I get a link or username ??

same 
krishna-NIT

**Comment by nidhivanjare** [comment]
yess
but I would need your 4 digit tag ??

**Comment by nidhivanjare** [comment]
DONE

**Pull request closed without merging**
