### PR TITLE
Added the code for Bitwise Operator Overloading #1701

### PR DESCRIPTION
**Pull request by Mugdha-Hazra**
Added C++ code for issue #1701 Bitwise Operator Overloading, @tarun26091999 @anubhavitis @veenit1802 @ssaksham @malavikarajeshvikraman @Rohan27s, @rish-singhal sir can you please review my code.

### CODE REVIEW

**Review by Rohan27s — CHANGES_REQUESTED** [review]
Kindly check out #1153 for the rules to contribute and update the read me file

**Comment by Mugdha-Hazra** [comment]
Hello, @Rohan27s, @rish-singhal sir I had updated the readme can you please review my code and tell me what else do I needed to modify.

**Comment by Rohan27s** [comment]
@Mugdha-Hazra You just have to add the question part... don't make any other change
Add here only-
image

**Comment by Mugdha-Hazra** [comment]
ok sir

**Comment by Mugdha-Hazra** [comment]
@Rohan27s sir I am not able to do it, I really tried a lot, can you please help me out? sir, can you please guide me through the steps to update the readme?

**Comment by Rohan27s** [comment]
You just need to add this - Bitwise Operator Overloading ---->[C++](/Code/C++/Bitwise_operator_overloading.cpp) in Algorithm/Bit_manipulation/readme.md and don't make any other changes in that file

**Comment by Mugdha-Hazra** [comment]
ok @Rohan27s  sir

**Pull request closed without merging**
