### PR TITLE
GeekonacciNo. --Python

### PR DESCRIPTION
**Pull request by U-c0de**
ISSUE :  #1764 

Do Check :  @rish-singhal  @Rohan27s

### CODE REVIEW

**Comment by U-c0de** [comment]
Do Check : @rish-singhal @Rohan27s

**Comment by U-c0de** [comment]
Do Check : @rish-singhal @Rohan27s

**Comment by U-c0de** [comment]
Do Check : @rish-singhal @Rohan27s

**Comment by Rohan27s** [comment]
Plagiarism from https://www.geeksforgeeks.org/geek-onacci-number/

**Comment by Rohan27s** [comment]
And you already have merged #1793 in C++ and you haven't asked any mentor to work on this issue in python

**Pull request closed without merging**
