### PR TITLE
Added Kernighan's Algorithm for bit masking in C++

### PR DESCRIPTION
**Pull request by Prajwal-ctrl**
Add description about : 
Where to use Kernighan's Algorithm ?
Why to use it ?
Test Cases 
Time Complexity

### CODE REVIEW

**Comment by Prajwal-ctrl** [comment]
Please review this commit i made it 20 days ago @aaadddiii @anubhavitis @veenit1802 @dheerajkotwani @

**Comment by Prajwal-ctrl** [comment]
@yasharth291 @yashmita @yashikajotwani12 
 Can you please tell where to mention the issue . I didn't get you, can you please guide me through it

**Comment by yasharth291** [comment]
@Prajwal-ctrl  you have to write Fixes #(your issue number here in the comment)

**Comment by Prajwal-ctrl** [comment]
@yasharth291 issues: #861

**Comment by Prajwal-ctrl** [comment]
@yasharth291 @aaadddiii please review this PR

**Review by yasharth291 — APPROVED** [review]

**Comment by Prajwal-ctrl** [comment]
@yasharth291 please merge this PR as soon as possible as it comes under GSSOC 21 PLEASE PLEASE
and last date is 31st I made this PR from long time

**Comment by tarun26091999** [comment]
issue already merged in all 3 language.

**Pull request closed without merging**
