### PR TITLE
Fixes #1704: Selection Sort in Python

### LINKED ISSUE #1704: Add Selection Sort implemented in Python
I would like to implement the selection sort algorithm in Python. 
@yasharth291 Can you please assign this to me?

### PR DESCRIPTION
**Pull request by Pushpit07**
Fixes #1704  : Added code that implements selection sort in Python

### CODE REVIEW

**Comment by Pushpit07** [comment]
This closes #1704

**Comment by yasharth291** [comment]
please write Fixes # (your issue number In this form)

**Comment by yasharth291** [comment]
plagrised from https://www.geeksforgeeks.org/python-program-for-selection-sort/

**Comment by Pushpit07** [comment]
Oh, so plagiarism is not allowed? I didn't know that. Sorry for this. Will write this on my own now

**Pull request closed without merging**
