### PR TITLE
Added Linked List code in python

### LINKED ISSUE #29: Linked List in python
I want to add linked list program in python. Please assign it to me.

### PR DESCRIPTION
**Pull request by sujoy-coder**
fixes #29 
Hi @rudrakshi99 , I have written the code for linked list in python with explanation and also I have been selected for GSSOC'21. Please review my request.
Let me know if any changes are required. 

Thank You  😊

### CODE REVIEW

**Review by raksha009 — CHANGES_REQUESTED** [review]
Plz go though the guidelines properly and link it to the proper folder.

**Comment by sujoy-coder** [comment]
Hi @raksha009 , I have made the requested changes. Please check it and let me know anything more required 🙏

**Comment by sujoy-coder** [comment]
Hello @raksha009, Can you please put a `gssoc21` label in this PR 👀 
and waiting for get it marge.

Thank You...

**Comment by raksha009** [comment]
Plz resolve merge conflicts :)

**Comment by sujoy-coder** [comment]
Hi @raksha009 , I have resolved the merge conflicts. Please check it.
One more request please give the **label for difficulty** 

Thank You...

**Comment by rudrakshi99** [comment]
> fixes #29
> Hi @rudrakshi99 , I have written the code for linked list in python with explanation and also I have been selected for GSSOC'21. Please review my request.
> Let me know if any changes are required.
> 
> Thank You

Please make PR after the issue gets assigned to you. This PR is against our guidelines.

**Review by rudrakshi99 — APPROVED** [review]

**Pull request merged**
