### PR TITLE
Kth min element in Array in JAVA

### PR DESCRIPTION
**Pull request by krishna-NIT**
#162 done in java
Kth minimum element in Array in JAVA
@nakul-19 @rudrakshi99 @tarun26091999

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
this is not the most optimized approach. You took this long to raise the PR and still the solution is nowhere near to the required quality. Also there are conflicts in code base.

**Comment by krishna-NIT** [comment]
@tarun26091999 will resolve it asap

**Comment by tarun26091999** [comment]
@krishna-NIT do it fast else we have to close the PR.

**Comment by krishna-NIT** [comment]
@yasharth291 Please Review my Code

**Comment by krishna-NIT** [comment]
@yasharth291 Please review it because Daily I get Conflicts in Readme File, I have to Resolve them Daily, Am I making any Mistake in Readme ?, can you please tell me why I am Getting Conflicts in Readme always, coz I am new to GIT and GITHUB

**Pull request closed without merging**
