### PR TITLE
Create factorial_using_recursion.cpp

### PR DESCRIPTION
**Pull request by tanyalava**

### CODE REVIEW

**Comment by sayantani11** [comment]
Link your PR to the issue you solved

**Comment by tanyalava** [comment]
I am new to open source that's why having problem linking it. Can you help me out.

**Comment by sayantani11** [comment]
@tanyalava  yes tell me

**Comment by tanyalava** [comment]
I am writing down all the steps I followed. Correct me if I am wrong somewhere.
1. fork the repository Algo-Tree
2 Created folder on desktop and opened it and inside folder, I opened git bash.
3 these are the commands I used on git bash
    git init 
    git clone (the link of the forked repo)
4 Then I move to the C++ folder inside the Code folder and then added a new file named factorial_using_recursion.cpp and then 
    add the code to the file.
5 git add factorial_using_recursion.cpp
6 git commit -m "changes added"
7 git push
8 and then I created a pull request

**Comment by tanyalava** [comment]
If I am not following the correct sequence, can you tell me the right one.

**Comment by sayantani11** [comment]
Create another branch from main using "git branch <example>"
and keep following from 4th step after it....It's not right to code on the main/master branch 
and also add #issue_no in the comments.

**Comment by tanyalava** [comment]
Thanks for the help

**Pull request closed without merging**
