### PR TITLE
Added the solution to check if a binary tree is a binary search tree in Java.

### PR DESCRIPTION
**Pull request by Meghna180401**
### Description
Implemented the solution to check if a binary tree is a Binary Search Tree in Java.
Included algorithmic explanations, sample test cases as well as space and time complexities

This contribution is as a part of GSSOC'21.

### CODE REVIEW

**Comment by Meghna180401** [comment]
@rudrakshi99 @tarun26091999 Kindly review this PR which I opened 4 days back and suggest required changes.

**Comment by Meghna180401** [comment]
There was some issue with my local branch which caused some unnecessary commits.
Should I close this and open a new pull request ? @tarun26091999 

I am sorry for the fault on my part.

**Comment by raksha009** [comment]
> There was some issue with my local branch which caused some unnecessary commits.
> Should I close this and open a new pull request ? @tarun26091999
> 
> I am sorry for the fault on my part.

Hey, if you could merge your commits and delete extra files in this pr, plz do so else if you feel, its a bit complicated and messed up, you could always open a new pr and close this one :)

**Comment by Meghna180401** [comment]
> > There was some issue with my local branch which caused some unnecessary commits.
> > Should I close this and open a new pull request ? @tarun26091999
> > I am sorry for the fault on my part.
> 
> Hey, if you could merge your commits and delete extra files in this pr, plz do so else if you feel, its a bit complicated and messed up, you could always open a new pr and close this one :)

Thanks @raksha009 . I really feel it has got messed up and would prefer opening a new PR.

**Pull request closed without merging**
