### PR TITLE
Shell sort using C++

### LINKED ISSUE #124: Add Sorting Algorithms
- [x] C++
    - [ ] Bubble Sort
    - [ ] Insertion Sort
    - [ ] Selection Sort
    - [ ] Merge Sort
    - [ ] Quick Sort
 - [x] Java
    - [x] Bubble Sort
    - [x] Insertion Sort
    - [x] Selection Sort
    - [ ] Merge Sort
    - [ ] Quick Sort
- [x] Python
    - [ ] Bubble Sort
    - [ ] Insertion Sort
    - [ ] Selection Sort
    - [ ] Merge Sort
    - [ ] Quick Sort

### PR DESCRIPTION
**Pull request by EkjotKaur**
Code for Shell Sort in C++
with commented

definition
input and output
time & space complexity 

shellSort

Fixed #124
Please view my PR @tarun26091999

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
link issue and folder here also. Add proper comments.

**Comment by plazzy99** [comment]
Please resolve the conflicts

**Comment by EkjotKaur** [comment]
@plazzy99 I have resolved conflicts.

**Review by plazzy99 — APPROVED** [review]
LGTM  👍🏻

**Pull request merged**
