### PR TITLE
Queue implementation using linkedlist added  

### LINKED ISSUE #59: Add Queue implementation using linked list in c++

### PR DESCRIPTION
**Pull request by Subhangini**
Fixes #59

### CODE REVIEW

**Comment by Subhangini** [comment]
Add gssoc and level label

**Review by nakul-19 — CHANGES_REQUESTED** [review]
@Subhangini please remove the unrelated file and make changes in the related readme.

**Comment by Subhangini** [comment]
> @Subhangini please remove the unrelated file and make changes in the related readme.

which file ? Are you talking about the readme file i have created? That readme file is just for the queue program which i have made,  it will clear the doubts of the user about the program and will give them an idea about the workflow  of program. And it is also acting as test cases

**Comment by Subhangini** [comment]
Review the changes @nakul-19

**Comment by nakul-19** [comment]
> Review the changes @nakul-19

Since pr solves #59 only remove the unrelated file, i.e., Factorial one.

**Comment by Subhangini** [comment]
> > Review the changes @nakul-19
> 
> Since pr solves #59 only remove the unrelated file, i.e., Factorial one.
> Also, remove the conflict.

Ok

**Comment by Subhangini** [comment]
Review the changes @nakul-19

**Comment by yasharth291** [comment]
GTG

**Review by yasharth291 — APPROVED** [review]

**Pull request merged**
