### PR TITLE
Job sequencing problem

### PR DESCRIPTION
**Pull request by vanshikachokhani**
### Changes made
I have written greedy approach to find the maximum profit in C++.
This is a small contribution as a part of GSSoC21.

I have tested the code and it works fine for every test case and included some sample test cases and also the algorithm.

### CODE REVIEW

**Review by OjusWiZard — CHANGES_REQUESTED** [review]
Add inline comments in the code sections to explain what the loop is for etc...

**Comment by vanshikachokhani** [comment]
Can you please reactivate the issue as I was not able to complete the work assigned. I aasure this delay won't happen again.

**Comment by raksha009** [comment]
> Can you please reactivate the issue as I was not able to complete the work assigned. I assure you this delay won't happen again.

Sure.

**Comment by vanshikachokhani** [comment]
> > Can you please reactivate the issue as I was not able to complete the work assigned. I assure you this delay won't happen again.
> 
> Sure. Plz do the changes asap

I have done all the requested changes. Thank You

**Review by raksha009 — CHANGES_REQUESTED** [review]
Plz go through the guidelines and pinned issues and link yr code to the required folder.

**Comment by vanshikachokhani** [comment]
> Plz go through the guidelines and pinned issues and link yr code to the required folder.

I have tried to update the readme but it is giving conflicts. Can you please guide me what to do.

**Comment by vanshikachokhani** [comment]
The PR is merged but the score for the PR is not updated can u please help @yasharth291 .

**Comment by yasharth291** [comment]
@vanshikachokhani sorry for delay i have added the labels

**Comment by vanshikachokhani** [comment]
> @vanshikachokhani sorry for delay i have added the labels

@yasharth291 Thank You. No issue

**Pull request merged**
