### PR TITLE
Added balanced brackets in python issue #217

### PR DESCRIPTION
**Pull request by anish-cpu**
Added balanced brackets in python Issue: #217

### CODE REVIEW

**Comment by anish-cpu** [comment]
@plazzy99 please review my PR #830 for issue #217

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
Do proper indentation in comments. Resolve the conflicts. Add complexities at the bottom, add comments explaining your code.

**Review by plazzy99 — APPROVED** [review]
do requested changes by @tarun26091999

**Comment by plazzy99** [comment]
Also resolve merge conflicts

**Comment by yasharth291** [comment]
@plazzy99 is it inactive

**Pull request closed without merging**
