### PR TITLE
K largest elements ---> Closes : [#1752]

### PR DESCRIPTION
**Pull request by Prerna-07**
closes : #1752

### CODE REVIEW

**Comment by Prerna-07** [comment]
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 pls check

**Comment by Prerna-07** [comment]
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 pls check

**Comment by Rohan27s** [comment]
@Prerna-07 Remove the conflicts

**Comment by Prerna-07** [comment]
@Rohan27s done sir pls check

**Review by Rohan27s — APPROVED** [review]

**Pull request merged**
