### PR TITLE
Stock Span Problem

### PR DESCRIPTION
**Pull request by Shreyash41**
## DESCRIPTION
**Implemented Stock Span Problem in the stack using C++ Language.**
Please review this PR.
## Issue
#709

### CODE REVIEW

**Comment by rudrakshi99** [comment]
https://github.com/Algo-Phantoms/Algo-Tree/tree/main/Stack the link to your problem is not working. Changed the folder and push your code to the `Code` folder.

**Comment by Shreyash41** [comment]
@rudrakshi99 You mean i push my solution to **Code -> C++ -> mycode** ??

**Comment by rudrakshi99** [comment]
> @rudrakshi99 You mean i push my solution to **Code -> C++ -> mycode** ??

yes.

**Comment by Shreyash41** [comment]
@rudrakshi99 You have closed this PR. Should I make another??

**Comment by rudrakshi99** [comment]
> @rudrakshi99 You have closed this PR. Should I make another??

yes

**Comment by Shreyash41** [comment]
@rudrakshi99 Please check my New PR. Please update me if it is correct or not?

**Pull request merged**
