### PR TITLE
Inverse of an array Added #847

### PR DESCRIPTION
**Pull request by krishna-NIT**
#847 Done
@rudrakshi99 @OjusWiZard @nakul-19
Please Review it

### CODE REVIEW

**Comment by krishna-NIT** [comment]
@yasharth291 Please Review my Code

**Comment by krishna-NIT** [comment]
@yasharth291 Please review it because Daily I get Conflicts in Readme File, I have to Resolve them Daily, Am I making any Mistake in Readme ?, can you please tell me why I am Getting Conflicts in Readme always, coz I am new to GIT and GITHUB

**Comment by krishna-NIT** [comment]
@rish-singhal Please Review it and please tell me if any changes

**Comment by krishna-NIT** [comment]
@Rohan27s @tarun26091999  Please Review it and Let me Know if any changes

**Review by Rohan27s — APPROVED** [review]

**Pull request merged**
