### PR TITLE
factorial using recursion added

### PR DESCRIPTION
**Pull request by tanyalava**

### CODE REVIEW

**Comment by OjusWiZard** [comment]
To which issue is it linked?

**Comment by tanyalava** [comment]
https://github.com/Algo-Phantoms/Algo-Tree/issues/276

**Review by raksha009 — COMMENTED** [review]
Hey, it shows an empty file!

**Comment by tanyalava** [comment]
I was  not aware of the same. I'll work on that.

**Comment by tanyalava** [comment]
Changes have been done!

**Review by raksha009 — COMMENTED** [review]
Link your code to appropriate folder. Plz go through the guildlines.

**Pull request closed without merging**
