### PR TITLE
Linked list intersection

### PR DESCRIPTION
**Pull request by vanshikachokhani**
#### Changes made
I have written an optimised approach for finding the intersection node of two singly linked lists in C++
This is a small contribution as a part of GSSoC21.

I have tested the code and it works fine for every test case and included some sample test cases and also the algorithm.

### CODE REVIEW

**Review by plazzy99 — CHANGES_REQUESTED** [review]
Make 2 separate issues for them also make sure to update the readme

**Comment by rudrakshi99** [comment]
@vanshikachokhani Remove 2D Matrix Rotation file.

**Comment by vanshikachokhani** [comment]
> @vanshikachokhani Remove 2D Matrix Rotation file.

I have deleted the 2d matrix rotation file.

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
make it user driven program, take inputs from the user.

**Pull request closed without merging**
