### PR TITLE
Selection sort in Python

### LINKED ISSUE #1704: Add Selection Sort implemented in Python
I would like to implement the selection sort algorithm in Python. 
@yasharth291 Can you please assign this to me?

### PR DESCRIPTION
**Pull request by Pushpit07**
Fixes #1704 : Added code that implements selection sort in Python

### CODE REVIEW

**Comment by yasharth291** [comment]
change the readme please

**Comment by Pushpit07** [comment]
what do you mean? what should I change?

**Comment by yasharth291** [comment]
readme of the subject your pr falls under

**Comment by Pushpit07** [comment]
It's correct though. This is selection sort in python

**Comment by Pushpit07** [comment]
ping

**Comment by Pushpit07** [comment]
I did the required changes. @yasharth291 ping

**Review by yasharth291 — APPROVED** [review]

**Pull request merged**
