### PR TITLE
Reverse Individual Words in String in JAVA

### PR DESCRIPTION
**Pull request by krishna-NIT**
#416 issue resolved, Complete Optimized Solution with Test Cases and Complexity Mentioned,
Dear Maintainer of this repo, please tell me if any changes need, or else please merge my pull request.
@tarun26091999 @rudrakshi99 @plazzy99  @nakul-19 
#416  in JAVA by @krishna-NIT

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
link it to strings folder and add comments to explain your logic.

**Comment by krishna-NIT** [comment]
@tarun26091999 @nakul-19 @rudrakshi99 
Please Review My Pull Request all Changes made
Almost 27 days went off

**Comment by shreyanspoddar** [comment]
Resolve the conflict

**Comment by krishna-NIT** [comment]
@yasharth291 Please Review my Code

**Pull request merged**
