### PR TITLE
No. of times a sorted array is rotated using Binary search

### PR DESCRIPTION
**Pull request by Amit366**
issue : #169 

This program counts the number of times a sorted array is rotated using Binary search.

This is done using Java.

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
cannot solve multiple issue in same PR. resolve this or I have to close the PR.

**Comment by Amit366** [comment]
@tarun26091999 the first one is from another branch. In this PR there is only one issue

**Comment by Amit366** [comment]
@tarun26091999 I have sent 2 PRs so it is like that

**Comment by rish-singhal** [comment]
What are there 2 files? Shouldn’t it be only 1? 

Also, you need to update respective readme too

**Comment by Amit366** [comment]
@rish-singhal Now please merge it. Its only showing conflict errors

**Comment by Amit366** [comment]
The 2 files which are deleted are already merged. So don't worry about that

**Comment by Rohan27s** [comment]
@Amit366 You have to resolve the conflicts otherwise we can't merge your PR

**Comment by Amit366** [comment]
@Rohan27s I am not getting the option for resolving

**Comment by Amit366** [comment]
@Rohan27s atleast now merge it . Its been open since when.

**Review by Rohan27s — APPROVED** [review]

**Review by tarun26091999 — APPROVED** [review]

**Pull request merged**
