### PR TITLE
Fibonacci series In C++ #635

### PR DESCRIPTION
**Pull request by kanchan1910**
I have added the solution for the Fibonacci Series #635  issue

Kindly review this, if any changes required please let me know!
@tarun26091999 sir please check this
@rudrakshi99 ma'am please check this
Thank you

### CODE REVIEW

**Comment by kanchan1910** [comment]
@tarun26091999 sir Kindly check this and if changes required please let me know

**Comment by kanchan1910** [comment]
@tarun26091999 , sir , kindly review this

Thank you!

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
provide only the most optimized approach. also remove the .idea files and link your code in the readme file.

**Comment by tarun26091999** [comment]
@kanchan1910 do it soon or I have to close the PR.

**Comment by kanchan1910** [comment]
@tarun26091999 sorry for the delay will do it now only. Thanks

**Pull request closed without merging**
