### PR TITLE
Create selection_sort.py

### PR DESCRIPTION
**Pull request by Pushpit07**
Selection sort implemented for a Python array

### CODE REVIEW

**Comment by rish-singhal** [comment]
which issue is this for? can you link the issue

**Comment by Pushpit07** [comment]
ah, not for an issue. Selection sort for python was not implemented by anyone yet. So, I just did that

**Comment by yasharth291** [comment]
so @Pushpit07  you should open an issue and ask us to assign it to you then you can make the pull request

**Comment by Pushpit07** [comment]
oh, ok. Sure

**Comment by Rohan27s** [comment]
You can't work on any topic until you are assigned on the respective issue

**Pull request closed without merging**
