### PR TITLE
kth Max Element added in JAVA

### PR DESCRIPTION
**Pull request by krishna-NIT**
#162 Kth Maximum in Java Added in JAVA
Please REview it
@rudrakshi99 @nakul-19 @OjusWiZard @plazzy99

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
this is not the most optimized approach. You took this long to raise the PR and still the solution is nowhere near to the required quality. Also there are conflicts in code base.

**Comment by krishna-NIT** [comment]
@tarun26091999 will resolve it asap

**Comment by krishna-NIT** [comment]
@yasharth291 Please Review my Code

**Comment by krishna-NIT** [comment]
@yasharth291 Please review it because Daily I get Conflicts in Readme File, I have to Resolve them Daily, Am I making any Mistake in Readme ?, can you please tell me why I am Getting Conflicts in Readme always, coz I am new to GIT and GITHUB

**Comment by plazzy99** [comment]
> @yasharth291 Please review it because Daily I get Conflicts in Readme File, I have to Resolve them Daily, Am I making any Mistake in Readme ?, can you please tell me why I am Getting Conflicts in Readme always, coz I am new to GIT and GITHUB

Because every merge is making some changes to the readme.

If you add changes to readme in last 2nd or 3rd line might be you get less conflicts

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
best time complexity of this problem is O(k + (n-k)*Logk). Think beyond sorting, and we cannot keep asking you to change solution again and again. how the space complexity is O(1) if you are using merge sort??

**Pull request closed without merging**
