### PR TITLE
Added longest prefix suffix problem

### PR DESCRIPTION
**Pull request by ansi22**
Hey,

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99
Kindly check this out it will fix issue #499 ,i.e, longest prefix suffix problem.
Thankyou!

### CODE REVIEW

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
code is fine. Add some more comments explaining your steps. Also space complexity is wrong. Give proper indentation and link it to the correct folder. remove line 9.

**Comment by ansi22** [comment]
Kindly check it out @tarun26091999 !

**Comment by ansi22** [comment]
@tarun26091999 kindly check it out, I have made the changes.

**Comment by shahbazalam07** [comment]
I WANT TO CONTRIBUTE

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
you haven't linked it to the folder yet.

**Comment by ansi22** [comment]
@tarun26091999 Sir, I have linked the file in string folder under branch issue-499, is it not showing there. Please tell how should I proceed.

**Comment by ansi22** [comment]
@tarun26091999 Sir kindly review this.

**Comment by ansi22** [comment]
@rish-singhal can you please review it.

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
resolve the conflict.

**Comment by ansi22** [comment]
I have resolved the conflict @tarun26091999 kindly look into it.

**Review by tarun26091999 — APPROVED** [review]

**Comment by ansi22** [comment]
@tarun26091999 please once go through #899, scores for it didn't get updated 😅

**Pull request merged**
