### PR TITLE
Create sliding_window_maximum.cpp

### LINKED ISSUE #380: Sliding window maximum/minimum
A program to retrieve the maximum/minimum element of each k sized continuous window of an array in O(n) time complexity. A good example where deque is useful.

I am a GSSOC'21 participant, and I would like to contribute the C++ code for this problem. I will make sure that the code is commented properly and follows all the given guidelines. Please give me this opportunity. Thankyou!

### PR DESCRIPTION
**Pull request by sg-iitg**
Fixes #380

### CODE REVIEW

**Comment by sg-iitg** [comment]
@tarun26091999 Please review my PR linked to issue #380

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
check your code and link to the folder.

**Comment by sg-iitg** [comment]
@tarun26091999 please review, I have linked the code to readme. Is there anything else I am supposed to do?

**Review by tarun26091999 — CHANGES_REQUESTED** [review]
code is not linked properly.

**Pull request closed without merging**
